[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[project]
name = "auto-trainer"
description = "Autotrainer full application and libs"
license = { text = "MIT" }
requires-python = ">= 3.8"
dynamic = ["version"]  # handled by setuptools-scm
dependencies = [
    # requesting exact version for sub-auto-trainer projects,
    # given API can be still unstable.
    'auto-trainer-training == 0.9.15',
    'auto-trainer-api == 0.9.16',

    # CAN communication with pellet/tunnel boards:
    'pyjerrycan >= 1.2.5, < 2 ; platform_machine == "aarch64"',

    # FLIR/spinnaker camera
    'spinnaker-python >= 3.2, < 3.3 ; platform_machine == "aarch64"',

    'verboselogs >= 1.7, < 2',
    'coloredlogs >= 15, < 16',

    'deeplabcut == 2.3.9',  # famous deeplab

    'events >= 0.5, < 1',   # dynamic events callback handling
    'transitions >= 0.9.2, < 1',  # machine state transition handling

    'numpy >= 1.23.5, < 2',
    'opencv-python >= 4.10, < 5',
    'pandas >= 2, < 3',
    'psutil >= 7, < 8',  # for free disk space, notably
    'pyhumps >= 3.8, < 4',  # snake/camel case converter
    'pyyaml >= 6.0.2, < 7',
    'PySide6 == 6.6.1',
    'pyqtgraph >= 0.13.3, < 1',
    'QtAwesome == 1.3.0',

    'tensorflow >= 2.12, < 3 ; platform_machine != "aarch64"',       # for non-aarch64 platform only
    'tensorflow == 2.12.0+nv23.06 ; platform_machine == "aarch64"',  # for aarch64 platform only
    # for now let it be installed manually still.
    # Otherwise, we need to have some pip.conf having extra-index-url to nvidia, or PIP_EXTRA_INDEX_URL variable too.

    'watchdog >= 4, < 5',  # filesystem change monitoring

    'setuptools-scm',  # to allow get version from git when in editable mode,
    # without requiring to `pip install -e .` everytime you checkout something.

    'importlib-resources; python_version < "3.10"',
    'importlib-metadata; python_version < "3.10"'
]

[project.optional-dependencies]
test = [
    "pytest >= 8.2, < 9",
    "pytest-mock >= 3, < 4",
    "pytest-randomly >= 3, < 4",
    "pytest-cov >= 5, < 6",
    "pytest-benchmark >= 4, < 5",
    "coverage >= 7, < 8",
    "coverage-enable-subprocess ~= 1.0",
]

# can probably be removed
old_platform = [
    'pyserial == 3.5',
]


[project.scripts]
auto-trainer-local = "tools.acquisition.gui:main"
auto-trainer-headless = "tools.acquisition.headless:main"
# etc... but is same than:
# python -m tools.acquisition.headless   # for instance.
#

[tool.setuptools_scm]
write_to = "tools/autotrainer_version.txt"
git_describe_command = "git describe --tags --dirty --match 'v*' --abbrev=8"


[tool.setuptools.packages.find]
where = [
    "auto-trainer-behavior/src",
    "auto-trainer-core/src",
    "auto-trainer-device/src",
    "auto-trainer-inference/src",
    "auto-trainer-model/src",
    "auto-trainer-pyside/src",
    "auto-trainer-video/src",
    ".",  # for tools
]
include = [
    "autotrainer.*",
    "tools",
]
namespaces = true

[tool.setuptools.package-data]
# package = ["file", ...]
tools = ["autotrainer_version.txt"]
