[build-system]
requires = [
    "setuptools >= 61",
    'setuptools-scm >= 9.2.2, < 10',  # to allow get version from git when in editable mode,
    "tomli >= 2, < 3",  # for current setup.py
]
build-backend = "setuptools.build_meta"

[project]
name = "auto-trainer"
description = "Autotrainer full application and libs"
license = { text = "MIT" }
requires-python = ">= 3.8"
dynamic = ["version", "dependencies"]
# see setup.py
#dependencies = [
# ...
#]

[project.optional-dependencies]
test = [
    "pytest >= 8.2, < 9",
    "pytest-mock >= 3, < 4",
    "pytest-randomly >= 3, < 4",
    "pytest-cov >= 5, < 6",
    "pytest-benchmark >= 4, < 5",
    "coverage >= 7, < 8",
    "coverage-enable-subprocess ~= 1.0",
]

# can probably be removed
old_platform = [
    'pyserial == 3.5',
]


[project.scripts]
auto-trainer-local = "tools.acquisition.gui:main"
auto-trainer-headless = "tools.acquisition.headless:main"
# etc... but is same than:
# python -m tools.acquisition.headless   # for instance.
#

[tool.setuptools_scm]
write_to = "tools/autotrainer_version.txt"
git_describe_command = "git describe --tags --dirty --match 'v*' --abbrev=8"


[tool.setuptools.packages.find]
where = [
    # temporary until split in many repos:
    "auto-trainer-behavior/src",
    "auto-trainer-core/src",
    "auto-trainer-device/src",
    "auto-trainer-inference/src",
    "auto-trainer-model/src",
    "auto-trainer-pyside/src",
    "auto-trainer-video/src",
    ".",  # for tools
]
include = [
    "autotrainer.*",
    "tools",
]
namespaces = true

[tool.setuptools.package-data]
# package = ["file", ...]
tools = ["autotrainer_version.txt"]
