
# Using empty (for now) pytest.ini file,
# this allows to force rootdir to the same directory than this file.
# Sub-allowing the top-level conftest.py file to be loaded and our custom pytest markers/options too.

# do not remove.

# See: https://docs.pytest.org/en/stable/reference/customize.html#finding-the-rootdir

[pytest]
# pytest options goes here
