from typing import Protocol

from autotrainer.core import MotorConfigurations, Offset3DTuple


class DeviceConnectionProtocol(Protocol):
    @property
    def read_limit(self) -> int: ...

    @read_limit.setter
    def read_limit(self, value: int): ...

    def request_connect(self): ...

    def request_disconnect(self): ...

    def join(self): ...

    def send_message(self, kind: int, data: object = None, context: object = None): ...

    def use_motor_configurations(self, data: MotorConfigurations): ...

    def set_motor_drift(self, drift: Offset3DTuple): ...
