from typing import Protocol, Callable, Tuple, Optional, Any

from autotrainer.core import Offset3DTuple, ObservableObject, FrameIndexCategory
from autotrainer.core.project import ProjectDependentProtol, ProjectInfo
from autotrainer.core.configuration.inference_configuration import InferenceConfiguration

import autotrainer.inference.analysis
from autotrainer.inference import InferenceStatus, PoseAlgorithm, InferenceMonitorDataMsg

from . import SegmentationConfiguration, DetectionConfiguration


class InferenceEvents:

    segmentation_finished = Callable[[bool], None]
    detection_result_ready = Callable[[ProjectInfo, autotrainer.inference.analysis.IntersessionResponse], None]
    pose_response_ready = Callable[[autotrainer.inference.PoseResponse], None]
    algo_initialised = Callable[[autotrainer.inference.PoseAlgorithm], None]  # not used by any listener
    diamond_triangle_offset_changed = Callable[[Optional[Offset3DTuple]], None]
    star_triangle_offset_changed = Callable[[Optional[Offset3DTuple]], None]
    triangle_pellet_offset_changed = Callable[[Optional[Offset3DTuple]], None]


class _InferenceProtocol(Protocol):

    status: InferenceStatus

    def stop(self):
        """Stop inference ; it can still be restarted after"""

    def terminate(self):
        """Terminate totally"""

    def load_configuration(self, config: InferenceConfiguration):
        """Load the given configuration"""

    def save_configuration(self) -> InferenceConfiguration:
        """Returns current configuration"""

    @property
    def pose_algorithm(self) -> PoseAlgorithm:
        """Current associated pose_algo"""

    @property
    def is_enabled(self) -> bool:
        """Wether enabled or not"""
        return False

    def perform_segmentation(self, configuration: SegmentationConfiguration) -> Optional[SegmentationConfiguration]:
        """Perform segmentation with given segment config, returns the passed config if succeeded, else None"""

    def perform_detection(self, configuration: DetectionConfiguration) -> Optional[DetectionConfiguration]:
        """Perform detection with given segment config, returns the passed config if succeeded, else None"""

    def perform_live(self):  # unused
        """Perform live"""

    def send_message(self, kind: "InferenceCommandMessageKind", context: Any = None):
        """Send an InferenceCommandMessageKind to the inference process"""

    def put_to_offline_queue(self, frame_index: FrameIndexCategory, *, reason: str="na"):
        """Put given frame index batch to offline queue"""

    def put_to_data_handler(self, msg: InferenceMonitorDataMsg):
        """Put msg to data handler"""


class InferenceProtocol(ObservableObject, _InferenceProtocol, ProjectDependentProtol):

    STATUS = "status"

    # "dynamic" event handler attributes,
    # we must not define as real methods in the protocol,
    # otherwise that's taking over the dynamic one being generated by Events, which break these events handling.
    # only defining as type hints,
    # to be more friendly/correct with IDEs and dynamic attributes accesses.
    segmentation_finished: InferenceEvents.segmentation_finished
    detection_result_ready: InferenceEvents.detection_result_ready
    pose_response_ready: InferenceEvents.pose_response_ready
    algo_initialised: InferenceEvents.algo_initialised
    diamond_triangle_offset_changed: InferenceEvents.diamond_triangle_offset_changed
    star_triangle_offset_changed: InferenceEvents.star_triangle_offset_changed
    triangle_pellet_offset_changed: InferenceEvents.triangle_pellet_offset_changed

    def __init__(self):
        super().__init__(event_names=tuple(attr for attr in dir(InferenceEvents) if not attr.startswith("_")))
