from dataclasses import dataclass
from typing import Protocol, Callable, Tuple, Optional

from autotrainer.core import Offset3DTuple, ObservableObject
from autotrainer.inference import InferenceStatus


# NB: not importing autotrainer.inference

from autotrainer.inference import PoseAlgorithm
# prevents increased chance of import loop/cycle,
# given, for instance, InferenceProtocol is subclassed by InferenceModel which is also referred to by PoseAlgo


@dataclass
class SegmentationConfiguration:
    nonce: str
    session_index: int
    complete: Callable[[str, bool], None]


@dataclass
class DetectionConfiguration:
    nonce: str
    complete: Callable[[str, bool], None]


class _InferenceProtocol(Protocol):

    status: InferenceStatus

    @property
    def pose_algorithm(self) -> "autotrainer.inference.PoseAlgorithm": ...

    def perform_segmentation(self, configuration: SegmentationConfiguration): ...

    def perform_detection(self, configuration: DetectionConfiguration): ...

    def perform_live(self): ...

    def set_inference_to_online(self): ...

    # "dynamic" event handler attributes,
    # we must not define as real methods in the protocol,
    # otherwise that's taking over the dynamic one being generated by Events, which break these events handling.
    # only defining as type hints,
    # to be more friendly/correct with IDEs and dynamic attributes accesses.
    detection_result_ready: Callable[["autotrainer.behavior.analysis.IntersessionResponse"], None]
    pose_response_ready: Callable[["autotrainer.inference.PoseResponse"], None]
    algo_initialised: Callable[["autotrainer.inference.PoseAlgorithm"], None]
    diamond_triangle_offset_changed: Callable[[Optional[Offset3DTuple]], None]
    star_triangle_offset_changed: Callable[[Optional[Offset3DTuple]], None]



class InferenceProtocol(ObservableObject, _InferenceProtocol):

    STATUS = "status"


if __debug__ and False:
    import autotrainer.inference
    import autotrainer.behavior.analysis.intersession_process
