[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["autotrainer"]
namespaces = true

[project]
name = "auto-trainer-pyside"
version = "1.0.0"
description = "Pyside6 extensions for autotrainer"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "PySide6",
    "pyqtgraph"
]

