[build-system]
requires = [
    "setuptools >= 61",
    'setuptools-scm >= 9.2.2, < 10',
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["autotrainer.inference", "autotrainer.inference.*"]
namespaces = true

[project]
name = "auto-trainer-inference"
description = "Network implementations for autotrainer"
license = { text = "MIT" }
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [

    "auto-trainer-core",

    'deeplabcut >= 2.3.11, < 2.4',  # famous deeplab

    'tensorpack >= 0.11, < 1',
    'tf-slim >= 1.1, < 2',
    # NB: tensorpack and tf-slim are used/required by deeplabcut, even tough they are not depended on by it,
    # so we explicitly add them here.

    'torch == 2.1.0a0+41361538.nv23.6 ; platform_machine == "aarch64"',
    # ensure we get/specify the desired version from nvidia for aarch64 ( == Jetson)

    'pandas >= 2, < 3',
    'numpy >= 1.23.5, < 2',

    'tensorflow >= 2.12, < 3 ; platform_machine != "aarch64"',       # for non-aarch64 platform only
    'tensorflow == 2.12.0+nv23.06 ; platform_machine == "aarch64"',  # for aarch64 platform only
    # for now let it be installed manually still.
    # Otherwise, we need to have some pip.conf having extra-index-url to nvidia, or PIP_EXTRA_INDEX_URL variable too.

]

[tool.setuptools_scm]
root = ".."
write_to = "auto-trainer-inference/src/autotrainer/inference/version.txt"
git_describe_command = "git describe --tags --dirty --match 'v*' --abbrev=8"
