[build-system]
requires = [
    "setuptools >= 61",
    'setuptools-scm >= 9.2.2, < 10',
]
build-backend = "setuptools.build_meta"

[project]
name = "auto-trainer-tools"
description = "Autotrainer full application and libs"
license = { text = "MIT" }
requires-python = ">= 3.8"
dynamic = ["version"]
dependencies = [
    # requesting exact version for auto-trainer standalone projects,
    # given API can be still unstable.
    'auto-trainer-training == 0.9.27',
    # NB: auto-trainer-api is coming via auto-trainer-core

    # but not already for these, still parts of this repo:
    'auto-trainer-behavior',
    'auto-trainer-video',
    'auto-trainer-device',
    'auto-trainer-pyside',
    'auto-trainer-model',

    # NB: prefer to set dependencies version specifier(s) in this pyproject dependencies:

    'setuptools-scm >= 9.2.2, < 10',  # to allow get version from git when in editable mode,
    # without requiring to `pip install -e .` everytime you checkout something.

    'importlib-resources; python_version < "3.10"',
    'importlib-metadata; python_version < "3.10"'
]


# following are currently in top level pyproject.toml :
# not sure if keep in top-level or move here yet...

#[project.scripts]
#auto-trainer-local = "tools.acquisition.gui:main"
#auto-trainer-headless = "tools.acquisition.headless:main"
## etc... but is same than:
## python -m tools.acquisition.headless   # for instance.
##
#
#[tool.setuptools_scm]
#root = ".."
#write_to = "tools/autotrainer_version.txt"
#git_describe_command = "git describe --tags --dirty --match 'v*' --abbrev=8"
#
#[tool.setuptools.packages.find]
#where = [
#    ".",  # for tools
#]
#include = [
#    "tools",
#]
#namespaces = true
#
#[tool.setuptools.package-data]
## package = ["file", ...]
#tools = ["autotrainer_version.txt"]
