on:
  push:
    branches:
      - main
      - develop
      - github-actions
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      pytest_extra_args:
        description: 'Extra args for pytest'
        required: true
        default: ''
        type: string
concurrency:  # allow cancel if new commit pushed
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    name: Setup env. and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    env:
      FORCE_COLOR: '1'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # required for real data test files
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project and dependencies
        shell: bash  # this is to get color output
        env:
          TERM: xterm-256color
        run: |
          set -x
          pip config --user set install.progress_bar off
          pip config --user set install.color always
          pip config --user set global.color always
          # NB: colors only apply to some of pip error/warning messages, or its progress bar but we disabled it. 
          pip install --upgrade pip  # might be risky
          pip -V
          cat /home/runner/.config/pip/pip.conf
          pip install -e ".[test]"
#          pip install -r requirements.txt
#          pip install -r requirements-test.txt
      - name: Show current version
        run: python -m setuptools_scm
      - name: Test with pytest
        run: |
          set -x
          export PYTEST_ADDOPTS="--color=yes"
          export COVERAGE_PROCESS_START="$PWD/.coveragerc"
          site_pkgs_dir=$(python -c "import site; print(site.getsitepackages()[0])")
          echo "import coverage; coverage.process_startup()" > "${site_pkgs_dir}/usercustomize.pth"
          coverage run -m pytest -v -s ${{ github.event.inputs.pytest_extra_args }}
      - name: Coverage
        run: |
          set -x
          coverage combine
          coverage html
          #
          echo "FULL COVERAGE"
          coverage report
          #
          # extra detail:
          echo
          for module in tools/acquisition $(find . -type d -name "auto-trainer-*" | sort)
          do
            # need relative to ./ (strip front ./) :
            module=$(realpath -s --relative-to ./ "${module}")
            echo "${module} COVERAGE"
            with_auto_trainer_src_dir="${module}/src/autotrainer"
            if test -d "${with_auto_trainer_src_dir}"
            then
              include="${with_auto_trainer_src_dir}/*"
            else
              include="${module}/*"
            fi
            coverage report --include="${include}" || true
            echo
          done
