on:
  push:
    branches:
      - main
      - develop
      - github-actions
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      pytest_extra_args:
        description: 'Extra args for pytest'
        required: true
        default: '-k training_plan --log-cli-level=DEBUG'
        type: string

jobs:
  build-and-test:
    name: Setup env. and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true  # required for real data test files
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          export FORCE_COLOR=1
          python -m pip config --user set global.progress_bar off
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: Test with pytest
        run: |
          export PYTEST_ADDOPTS="--color=yes"
          coverage run -m pytest -v -s ${{ github.event.inputs.pytest_extra_args }}
      - name: Coverage
        run: |
          coverage html
          coverage report
