[build-system]
requires = [
    "setuptools >= 61",
    'setuptools-scm >= 9.2.2, < 10',
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["autotrainer.device", "autotrainer.device.*"]
namespaces = true

[project]
name = "auto-trainer-device"
description = "Device implementations for autotrainer"
license = { text = "MIT" }
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "auto-trainer-core",

    'pyyaml >= 6.0.2, < 7',

    # CAN communication with pellet/tunnel boards:
    'pyjerrycan >= 1.2.5, < 2 ; platform_machine == "aarch64"',
]

[tool.setuptools_scm]
root = ".."
write_to = "auto-trainer-device/src/autotrainer/device/version.txt"
git_describe_command = "git describe --tags --dirty --match 'v*' --abbrev=8"
